### ISSUE TITLE
Versions since 10 seem to aggressively start in the foreground on 14.04 and 16.04. On 16.04 rexray will not even start.

### ISSUE THREAD

**Issue by rlewkowicz** [thecodeteam/rexray#1103]
# Summary
I guess my big question is, what does your ideal functioning environment look like? What ami's do you prefer (if you even prefer amazon), what orchestration platform do you lean towards. I'm running into a lot of stuff just not working.

I'm trying to use rexray with the native docker driver:
https://hub.docker.com/r/rexray/ebs/

9.2 seems to be the most stable of the bunch (but again, some stuff just seems to not work). On 10+ on Ubuntu 16.04, rexray hangs on the splash screen aggressively and I get no debug output. On 14.04 it works much more smoothly, but still starts aggressively in the foreground and will not daemonize on a service start (at least not in the current tty, I think it's still starting as a service, there is at least a pid that also seems to be aggressively present). 

I can dig and provide log reports across the board, but I guess I'm just more interested in what a ideal functioning environment looks like and then I can go from there. I'm having a very hard time establishing a base line and saying "this works, lets build and adjust". I did read the docs, but things still just seem very off base.

**Comment by clintkitson** [comment]
Hello @rlewkowicz,

There was a change that was made around 0.10 which stop REX from forking itself to start properly in the background. I can let @akutz expand on why this was done. But the intention is if you are issuing a `start` command that it would investigate which init system you are currently running and start itself and thus fork itself using that.

Have you done a `rexray install`? This would actually deploy and configure the startup properly before trying to start.

Also, REX-Ray starting in the foreground is intentional now and likely to happen if an init system isn't detected. When you say it isn't working, are you sure it is not that REX is actually started and waiting listening for Docker? Have you tried issuing `docker volume ls` commands, etc once it has started?

Regarding debugging, have you tried REXRAY_DEBUG=true before the commands?
