### ISSUE TITLE
Allow modification of an existing volume's size 

### ISSUE THREAD

**Issue by cduchesne** [thecodeteam/rexray#585]
For block devices like EBS and ScaleIO, we should allow increasing volume size. For shared filesystems like EFS and Isilon, we should allow increased and decreasing of volume size.

**Comment by akutz** [comment]
Please update the description to include a note whether this means at the time a volume is created or after the fact. I'm not clear if the issue is referring to changing the default volume size for new volumes.

**Comment by cduchesne** [comment]
Modification means changing. I have updated title

**Comment by codenrhoden** [comment]
There would be two components to this -- the libS API changes to do the modification, and the REX-RAY CLI changes to use that new API. I'm going to copy this issue to libS capture the former.

**Comment by codenrhoden** [comment]
As we move to CSI, I believe we will only be adding this feature once CSI supports it. That will be in a future spec update. For CSI drivers, we can't even allow an "out of band" method for increasing the size (via REX-Ray, for example), because that would make the volume invalid per the spec (the volume wouldn't match what was requested).
